language: python
sudo: false
python:
  - "3.7"

install:
  - pip install bikeshed
  - bikeshed update

script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "3ed1c8db88ff"
  - COMMIT_AUTHOR_EMAIL: "public-w3process@w3.org"
